name: springwolf-amqp

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/springwolf-amqp.yml'
      - 'springwolf-core/**'
      - 'springwolf-examples/springwolf-amqp-example/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run integration tests
        run: ./gradlew -p springwolf-examples/springwolf-amqp-example test
